version: '2'
services:
  nginx_server:
    image: nginx:1.11.5-alpine
    ports:
      - "8081:80"
    links:
      - "fpm-server:fpm-server"
    volumes:
      - /opt/webroot/:/data/webroot/:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params.conf:ro
      - ./etc/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf:ro
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
  fpm-server:
    image: registry.cn-hangzhou.aliyuncs.com/c3t3m3/php-ci:aliyun
    volumes:
      - /opt/webroot/:/data/webroot/:ro

